name: Edge-agent

on:
  repository_dispatch:
    types:
      - 'edge-agent'

jobs:
  release:
    name: "Environments test workflow"
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ github.event.client_payload.component }}
      ENVIRONMENT: ${{ github.event.client_payload.env }}
      VERSION: ${{ github.event.client_payload.version }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run integration
        id: integration
        run: echo "RESULT=PASSED" >> $GITHUB_OUTPUT

      - name: Notify slack
        env:
          TEXT: "Integration ${{ env.COMPONENT }} v${{ env.VERSION}}: ${{ steps.integration.outputs.RESULT }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: npm run slack
