name: End-to-end integration

run-name: Testing '${{ github.event.client_payload.component }}' integration change

on:
  repository_dispatch:
    types:
      - 'cloud-agent'
      - 'edge-agent'
      - 'mediator'

permissions:
  contents: write

jobs:
  integrate:
    name: "Triggered from ${{ github.event.client_payload.component }} ${{ github.event.client_payload.env }}"
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ github.event.client_payload.component }}
      ENVIRONMENT: ${{ github.event.client_payload.env }}
      DEV_AGENT_URL: ${{ vars.DEV_AGENT_URL }}
      DEV_MEDIATOR_URL: ${{ vars.DEV_MEDIATOR_URL }}
      SIT_AGENT_URL: ${{ vars.SIT_AGENT_URL }}
      SIT_MEDIATOR_URL: ${{ vars.SIT_MEDIATOR_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run integration
        id: integration
        run: |
          npm ci
          npx run --component ${{ env.COMPONENT }} --env ${{ env.ENVIRONMENT }}

      - name: Notify slack
        if: failure()
        env:
          TEXT: "Resut of ${{ env.COMPONENT }} ${{ env.ENVIRONMENT}}: FAILED"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: node slack

      - name: Update reports
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add reports
          git commit -m "update reports for ${{ github.event.client_payload.component }}"
          git push

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./reports"

  update-site:
    needs: integrate
    name: Update report website
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
